In [1]:
import pandas as pd
pd.set_option('display.max_rows', None)


# Remplace par le chemin réel vers ton fichier Parquet
chemin_fichier = 'data/domains/domains_US.parquet'

# Lecture du fichier Parquet
df = pd.read_parquet(chemin_fichier)
df = df.sort_values(by='domain')  # Tri par nom de domaine pour une meilleure lisibilité

# Affichage du DataFrame (Jupyter le rendra sous forme de beau tableau interactif)
display(df)  # Tri par nom de domaine pour une meilleure lisibilité

# Optionnel : si ton fichier est énorme, affiche juste les 5 premières lignes
# display(df.head())

          id                          domain
426   103308                24hourhiphop.com
784   276336                     404media.co
1216   74622                     48hills.org
1522  254826                         7al.net
1067    5498                       abc27.com
1469   44765                     abcnews.com
1354    4218                aberdeennews.com
356    91627                  abilene-rc.com
118     2000                  abqjournal.com
399   192238                  accesswire.com
1274   52037                         acm.org
1542   13666                  actiontrip.com
1026  215520                     adaicon.com
206     8269          addisonindependent.com
1375  155072                    adelnews.com
1557     873                         adn.com
1973  263939             advertisergleam.com
326     2561               advocate-news.com
628    68373                aerotechnews.com
270   182910                   aframnews.com
834    94172                        afro.com
1183    5020                   ahwatukee.com
1673    2722               aikenstandard.com
291     8391                         aim.org
1636    1760                        aina.org
983     2735               airforcetimes.com
1073  170586                  airwaysmag.com
296     1029                         ajc.com
1012  211228                      ajnews.com
1521  165877                  akhonsamoy.com
1016   13056           akronnewsreporter.com
648     2240                  al-monitor.com
1421     399                          al.com
1558    3654                alachuatoday.com
1712   15202                  alamedasun.com
894     2776              alamogordonews.com
1443  268154                alaskabeacon.com
846    11246               alaskajournal.com
1835    6498                  alaskastar.com
1784     548                albanyherald.com
447    10029            albertleatribune.com
1698   78270                 aldiadallas.com
1696   11278             alexcityoutlook.com
1335    6457                  algemeiner.com
840    10359                      algona.com
1095    1687                       alibi.com
213     5882                   alligator.org
58     39814            allpointbulletin.com
1740   10730                 almanacnews.com
662     3143             alpineavalanche.com
926     2961               altoonamirror.com
1154    9964                  altustimes.com
1620  249897           alvareviewcourier.com
1964  176365                    ama-assn.org
71      1648                    amarillo.com
959     6124              americanbanker.com
277   163771           americanisraelite.com
93     20724                  amherstbee.com
583     9730             amherstbulletin.com
2052   14297            amityvillerecord.com
1134  187812                      amnews.com
553     2876                        amny.com
1223    8365               amsterdamnews.com
711   252407             anabaptistworld.org
276   109548                  anarchymag.org
116   119512               anarchyplanet.org
912    12193              anchoragepress.com
2003    4243           andalusiastarnews.com
737     7233             andovertownsman.com
1085  220669               andrewsmcmeel.com
564     5493                annistonstar.com
692      312                          ap.org
1850  101868                      apg-wi.com
290     1320                         app.com
220     5127                   appadvice.com
1196    2971             appeal-democrat.com
397   155045                 arcadianews.com
978   150761                     archive.org
1952    5309                   archpaper.com
1950    6373               argusobserver.com
363     8348                     arizona.edu
1341    4811              arkansasonline.com
969     2637                    arktimes.com
750     9178              armenianweekly.com
1653    2069                   armytimes.com
1171    5946                    artvoice.com
311     3934                     asbarez.com
1079    4085                   ashlandwi.com
1743    1967                asianjournal.com
1704   80796               asianreporter.com
1378    6893              aspendailynews.com
632     3431                  aspentimes.com
742    14700                  asurampage.com
1591     154              atascaderonews.com
448    53552            atchisonglobenow.com
1438    2809                athensreview.com
1832   16167              atholdailynews.com
680     3483            atlantablackstar.com
603      204           atlantadailyworld.com
1326    8520               atmoreadvance.com
1560    8684               auburnjournal.com
55      2115                   auburnpub.com
1803     473                     augusta.com
1914    1151             austinchronicle.com
655     9203           austindailyherald.com
1241   21082               austinmonitor.com
513   101313                       aut.ac.nz
765   222711                  avenuenews.com
2043   14913              avoyellestoday.com
496   229687                     avpress.com
924    11009             awfulannouncing.com
960   196041                       axios.com
134   148985             azbusinessdaily.com
1588    8346              azcapitoltimes.com
984     1248                   azcentral.com
1135     663                  azdailysun.com
610   230917                    azmirror.com
676     5154                badgerherald.com
508     5550            bainbridgereview.com
261    23845             bakercityherald.com
105    84400                 bakersfield.com
838    10570                 baldwincity.com
1921    3617          ballardnewstribune.com
1792   11475              ballstatedaily.com
163   213116               baltimorebeat.com
825   228675          baltimorechronicle.com
1721   23697            baltimoregaylife.com
598     1605                baltimoresun.com
1675   19911       baltimoretimes-online.com
922      440             bangordailynews.com
1188    5819                    bankrate.com
432   231462                   bankspost.com
624   157478              banner-tribune.com
1479   10332            baptistmessenger.com
861     9368             baptiststandard.com
1248   11799           barnstablepatriot.com
1512   19506             bartonchronicle.com
1895    3091           bastropenterprise.com
585     3610         battlecreekenquirer.com
909     1241              baxterbulletin.com
196   205235                     bayarea.com
1694   19357              baycitytribune.com
1280    6804                baylorlariat.com
1445  214142                  bayoubrief.com
1275  271442                baytobaynews.com
877      284                  baytownsun.com
327    56621                  bcdemocrat.com
1383    6178            bcdemocratonline.com
1144   48230                   bcheights.com
104      412                   bdtonline.com
1597  242532               beaconjournal.com
621    10632         beauregarddailynews.net
1268  288656                     beenews.com
771    13733               belgrade-news.com
1393   12136            bellinghamherald.com
1685    1110             beloitdailynews.com
1060    1483              bemidjipioneer.com
1750   66478                   benarnews.org
512     6734                bendbulletin.com
1782    2361                  bendsource.com
404   208351               benewsjournal.com
539    66330         beniciaheraldonline.com
1885    1381            benningtonbanner.com
1833   20890              bensonnews-sun.com
1089   15068               bentoncourier.com
1908   11723         berkeleydailyplanet.com
184      611              berkshireeagle.com
499    47483              berlindailysun.com
1858   15297            bestofneworleans.com
1607    9840                beverlypress.com
814   259265          bgindependentmedia.org
454    16516              bigbeargrizzly.net
1094   21548                  bigbugnews.com
128    83348             bigspringherald.com
1773    5832                bikeportland.org
1227    1862             billingsgazette.com
534   284980                  bioxconomy.com
139    64575             birminghamtimes.com
929      954             bismarcktribune.com
1204   20756              bitterrootstar.com
1044   13505                     bizbash.com
527      435                 bizjournals.com
336     4271                blabbermouth.net
1332   17541           blackmountainnews.com
1788   54494               blackstarnews.com
587    23563              blackvoicenews.com
1805  271461     blackwelljournaltribune.net
1878  224153            blockclubchicago.org
1925     262                   bloomberg.com
510   268583              bloomfieldinfo.org
606     4072                blueridgenow.com
1219    5260                blufftonicon.com
329    14021               blufftontoday.com
1623   11303                         bnd.com
1963    9778                      bocojo.com
2054   21272                    bohemian.com
11      3877                 boiseweekly.com
1692  148018                     bolavip.com
1516     865        bonnercountydailybee.com
373   266633               borderlessmag.org
1164  271524                borderreport.com
1490     271                      boston.com
1633    1059                 bostonglobe.com
1619      38                bostonherald.com
1735   10519               boulderweekly.com
1643   12556               bowdoinorient.com
1331    3307       bozemandailychronicle.com
6      81964                brandeishoot.com
547    11032         bransontrilakesnews.com
1048    7129                   breezejmu.org
944      460                   breitbart.com
303    74854                    brethren.org
82     18991             brewtonstandard.com
166   201248                bristolpress.com
1322  163755             broadsideonline.com
1328   11093               brooklyneagle.com
1546   15165               brooklynpaper.com
168   184361            brooklynreporter.com
1424    7867        broomfieldenterprise.com
942     6099            browardpalmbeach.com
1410    4246            browndailyherald.com
98      7375                 brownwoodtx.com
324    41699             brunswickbeacon.com
505     1781            brushnewstribune.com
670    72726               bryantarchway.com
782     1942     buckscountycouriertimes.com
223      685                 buffalonews.com
43     12567                 bupipedream.com
1969    5315           burlington-record.com
1161    1408       burlingtoncountytimes.com
1780    1435         burlingtonfreepress.com
1132   21753           burnstimesherald.info
4        425             businessinsider.com
1106  174319          businessinsider.com.pl
968   188715              businessinsider.nl
1663   23824          businessobserverfl.com
1586    2873    butlercountytimesgazette.com
87     19885                         byu.edu
288    53432                     c-ville.com
302     4619            cachevalleydaily.com
1283    4501                cadillacnews.com
1325   13640         calaverasenterprise.com
1590    4967            caledonianrecord.com
732   263428           calexicochronicle.com
1185  225238             calhealthreport.org
530    14408          californiademocrat.com
1720  233015             californiaglobe.com
1221    4464                      caller.com
1920  155362                  calmatters.org
1487   11397               camdenarknews.com
1286   13798               cameronherald.com
1033   54086                    campbell.edu
873    11925                 campustimes.org
1415    2835           cantondailyledger.com
49      2250                   cantonrep.com
824     9760                 canyon-news.com
1674  126190               canyoncourier.com
807     4098               capecodonline.com
162     1301                capecodtimes.com
1315    7049           capitalcityweekly.com
602     2582              capitalgazette.com
1537    3231                capitalpress.com
1842   49488       cardinalcourieronline.com
2031   12042                  carmitimes.com
89      3639          carrollcountytimes.com
386    11198               carrollspaper.com
460     3470               carthagepress.com
1684   14292                 carycitizen.com
729   267223               cascadiadaily.com
995     9209                catholicnews.com
2013    4865          catholicnewsagency.com
1452   10577            catholicsentinel.org
1736    1840               cavalierdaily.com
307   167861                   cayuga-cc.edu
1301    2194                     cbsnews.com
20     66734                 cccadvocate.com
870     4402                    cdapress.com
40     10044                         cdc.gov
459     3204                  cecildaily.com
1666   93544                     cengage.com
1035    6064           centerforpolitics.org
239     4471        centralfloridafuture.com
191     2964               centraljersey.com
1845     397                centralmaine.com
343    45988                 centredaily.com
1870   21959                cerescourier.com
2001   71376                        cf.ac.uk
381    21366                 cgmagonline.com
1394   41966                  cgsentinel.com
1677   12438          chaffeecountytimes.com
907     3492                   chalkbeat.org
697    10405          championnewspapers.com
1126   10622          charlestonbusiness.com
633     3941         charlestoncitypaper.com
330      119           charlotteobserver.com
921     5922               cheboygannews.com
312    13491               cherokeescout.com
403    24648              cheshireherald.com
1195   86358                       chess.com
1614   20637                 chetekalert.com
109     2633             chicagobusiness.com
1838    1724             chicagodefender.com
1657   12452               chicagomaroon.com
1660    6143               chicagoreader.com
2011     732              chicagotribune.com
1943    3158                     chicoer.com
1770    4497                   chieftain.com
393   132315           chilkatvalleynews.com
1043    1344          chillicothegazette.com
2029    2215           chinadigitaltimes.net
2016   15529             chinookobserver.com
899     2943               christianpost.com
1681    6394                   chronicle.com
536    11315             chronicleonline.com
1507   15391                   chronline.com
567   172681               churchleaders.com
345      933                  cincinnati.com
636     1850               citizen-times.com
304   133969                     citizen.com
793     5455               citizensvoice.com
1911   14733                    citybeat.com
1992   50144            cityonahillpress.com
2036    7736                   citypages.com
1741    1354                   citypaper.com
203     5638                  cityweekly.net
413   170044                   civilbeat.org
1865  157240                   civileats.com
637     2481                    cjonline.com
1730    6173           clantonadvertiser.com
254    12204           claremont-courier.com
433      458           claremoreprogress.com
1808    1685               clarionledger.com
704    46952        clarkecountydemocrat.com
319   151588           claxtonenterprise.com
1380   13519                       clclt.com
1459  253367          clearwaterprogress.com
1392  139998           clearwatertribune.com
1918   40611         cleburnetimesreview.com
175      368                   cleveland.com
1634    2391                  clevescene.com
453   182835                   clickhole.com
709     4802               clintonherald.com
943     1242                        cnbc.com
210     3238                   cnjonline.com
1056     462                         cnn.com
915   187021                 coastalview.com
1615    4193                   collegian.com
1864     334             collegiatetimes.com
1099    1256                  coloradoan.com
1742   44544      coloradocommunitymedia.com
1524    2221               coloradodaily.com
999    15493      coloradohometownweekly.com
1605  257588            coloradonewsline.com
1556    5172           coloradostatesman.com
569   223470       coloradotimesrecorder.com
1928    2208         columbiabasinherald.com
1237    1346         columbiadailyherald.com
1366     908          columbiamissourian.com
263      674                   columbian.com
1093    4190           columbiaspectator.com
835     3538             columbiatribune.com
57    222512           columbusmessenger.com
1717   24610                columbuspost.com
627      761            columbustelegram.com
596     2144                   comicbook.com
1775     985            commercialappeal.com
952    22962           commonwealthtimes.org
887    13983           communityadvocate.com
914   258168               communitynews.org
982   268115                  compactmag.com
1395    4118              concordmonitor.com
50    124484             concrete-herald.com
537   272569                 consequence.net
1180   82230          conservativereview.com
1538   68388          cooperpointjournal.com
605    19144             cordeledispatch.com
1561    3714                     cornell.edu
1344    2312                  cornellsun.com
993    12194              coronadonewsca.com
619     1896           corsicanadailysun.com
1118    4898            coshoctontribune.com
1192    1743                     courant.com
1483    2662             courier-journal.com
1302   15454               courierherald.com
1397    4512                 couriernews.com
1468    2748           courierpostonline.com
1998    1719                courierpress.com
774      701              courthousenews.com
417   238872            cowboystatedaily.com
240    73889             coyotechronicle.net
1841   12649             craigdailypress.com
1977    7059               crainsdetroit.com
681      678               crainsnewyork.com
1872   11228                    creators.com
1874    3935            crestedbuttenews.com
809     1494              crookstontimes.com
1417    3680                    crosscut.com
956      300                   csmonitor.com
266   241131                   ctinsider.com
1645     494                      ctpost.com
789    17592                      cubed3.com
142     2459                cullmantimes.com
832    96937            culturedvultures.com
645    16351          culvercityobserver.com
333     2087                currentargus.com
2060   21216                  currypilot.com
452     9767                     cvbugle.com
187   157424                 daily-iowan.com
1281    4900                  daily-jeff.com
1198    8679               daily-journal.com
661     1014                 daily-times.com
1062    2619                dailyadvance.com
186     3693               dailyadvocate.com
1990    3406               dailyastorian.com
355     6504              dailybarometer.com
236     2836                 dailybreeze.com
492     4955                  dailybruin.com
1404    4100               dailybulletin.com
1262    4145                    dailycal.org
1156    4765                   dailycall.com
1401    1643                 dailycaller.com
1831  184729   dailycallernewsfoundation.org
1659    2065                 dailycamera.com
1583   21175                 dailycampus.com
927   145263               dailycardinal.com
1207      43             dailycommercial.com
1339     996               dailydemocrat.com
495     2235                    dailydot.com
1265   23404                dailyemerald.com
144     8109              dailyevergreen.com
1458    2387                dailyfreeman.com
1913    2891               dailygamecock.com
990    48376                   dailyhome.com
1444    2629                 dailyillini.com
1206    4450            dailyindependent.com
483     1665              dailyinterlake.com
1843      93                dailyjournal.net
1912    2792          dailyjournalonline.com
684     6323                   dailylobo.com
1548  229487               dailymemphian.com
310   260448               dailymontanan.com
507     1981                   dailynews.com
388     4570                  dailynexus.com

In [9]:
import duckdb

# Chemin vers ton fichier Parquet brut
chemin_parquet = 'gdelt_parquet_db/gdelt_2015-02.parquet'

# On définit la limite pour la vérification
min_themes = 1 

# Requête de vérification sur les 5 premières lignes
query = f"""
SELECT 
    m.GKGRECORDID,
    strptime(substr(CAST(m.DATE AS VARCHAR), 1, 8), '%Y%m%d')::DATE AS period,
    CAST(m.Tone AS DOUBLE) AS tone,
    SIGN(CAST(m.Tone AS DOUBLE)) AS tone_bin,
    ARRAY_LENGTH(string_split(m.EnhancedThemes, ';')) AS total_themes_count,
    list_transform(
        string_split(m.EnhancedThemes, ';'),
        x -> upper(trim(split_part(trim(x), ',', 1)))
    ) AS themes_list
FROM '{chemin_parquet}' m
WHERE ARRAY_LENGTH(string_split(m.EnhancedThemes, ';')) >= {min_themes}
LIMIT 5
"""

# Exécution et affichage
resultat = duckdb.query(query).to_df()
display(resultat)

,GKGRECORDID,period,tone,tone_bin,total_themes_count,themes_list
0,20150219071500-0,2015-02-19,-4.644531,-1,86,"[KILL, SEIGE, CHECKPOINT, UNREST_CHECKPOINT, W..."
1,20150219020000-0,2015-02-19,-2.222656,-1,26,"[CRIME_COMMON_ROBBERY, CRIME_COMMON_ROBBERY, D..."
2,20150219020000-1,2015-02-19,-2.068359,-1,21,"[TRAFFIC, DISCRIMINATION, ARREST, TRIAL, TAX_F..."
3,20150219020000-2,2015-02-19,-2.250000,-1,14,"[GENERAL_GOVERNMENT, ECON_INTEREST_RATES, ECON..."
4,20150219020000-3,2015-02-19,-1.104492,-1,44,"[TAX_WORLDLANGUAGES, TAX_FNCACT, TAX_FNCACT, T..."

In [23]:
import duckdb
import pandas as pd

# 1. Connexion et configuration minimale
con = duckdb.connect()

# 2. Création de la structure de test (simulant la table gkg_clean)
# On utilise tes propres fonctions de transformation pour garantir la cohérence
query_setup = """
CREATE TABLE gkg_clean AS 
SELECT 
    GKGRECORDID,
    strptime(substr(CAST(DATE AS VARCHAR), 1, 8), '%Y%m%d')::DATE AS period,
    CAST(Tone AS DOUBLE) AS tone,
    SIGN(CAST(Tone AS DOUBLE)) AS tone_bin,
    ARRAY_LENGTH(string_split(EnhancedThemes, ';')) AS total_themes_count,
    list_transform(
        string_split(EnhancedThemes, ';'),
        x -> upper(trim(split_part(trim(x), ',', 1)))
    ) AS themes_list
FROM read_parquet('gdelt_parquet_db/gdelt_2015-02.parquet')
LIMIT 5;
"""
con.execute(query_setup)

# 3. Ton code de matching (copié depuis ton script)
# On enregistre une table de thèmes bidon pour tester le JOIN
sector_themes = pd.DataFrame({
    'cat_key': ['GENERAL_GOVERNMENT', 'TAX_WORLDLANGUAGES', 'CHECKPOINT'],
    'theme': ['GENERAL_GOVERNMENT', 'TAX_WORLDLANGUAGES', 'CHECKPOINT'] # Remplace par tes thèmes réels
})
con.register("sector_themes_tbl", sector_themes)

query_matching = """
WITH 
-- 1. Unnesting propre grâce à la liste pré-calculée dans gkg_clean
unnested AS (
    SELECT GKGRECORDID, period, tone, tone_bin, total_themes_count, unnest(themes_list) as theme
    FROM gkg_clean
),

-- 2. Matching exact avec les thèmes du secteur
matched AS (
    SELECT 
        u.GKGRECORDID, u.period, u.tone, u.tone_bin, u.total_themes_count,
        st.cat_key,
        COUNT(*) AS theme_hits
    FROM unnested u
    INNER JOIN sector_themes_tbl st ON u.theme = st.theme
    GROUP BY 1, 2, 3, 4, 5, 6
)

SELECT * FROM matched
"""

# 4. Affichage du résultat
resultat = con.execute(query_matching).df()
display(resultat)

,GKGRECORDID,period,tone,tone_bin,total_themes_count,cat_key,theme_hits
0,20150219071500-0,2015-02-19,-4.644531,-1,86,TAX_WORLDLANGUAGES,2
1,20150219020000-1,2015-02-19,-2.068359,-1,21,TAX_WORLDLANGUAGES,1
2,20150219071500-0,2015-02-19,-4.644531,-1,86,CHECKPOINT,1
3,20150219020000-2,2015-02-19,-2.250000,-1,14,GENERAL_GOVERNMENT,1
4,20150219020000-3,2015-02-19,-1.104492,-1,44,TAX_WORLDLANGUAGES,1

In [25]:
import duckdb
import pandas as pd

# Désactiver la limitation de largeur de colonne dans Jupyter
pd.set_option('display.max_colwidth', None)

con = duckdb.connect()

# 1. On récupère aussi la colonne originale 'EnhancedThemes' dans gkg_clean
query_setup = """
CREATE TABLE gkg_clean AS 
SELECT 
    GKGRECORDID,
    EnhancedThemes, -- On garde la version brute
    strptime(substr(CAST(DATE AS VARCHAR), 1, 8), '%Y%m%d')::DATE AS period,
    CAST(Tone AS DOUBLE) AS tone,
    SIGN(CAST(Tone AS DOUBLE)) AS tone_bin,
    ARRAY_LENGTH(string_split(EnhancedThemes, ';')) AS total_themes_count,
    list_transform(
        string_split(EnhancedThemes, ';'),
        x -> upper(trim(split_part(trim(x), ',', 1)))
    ) AS themes_list
FROM read_parquet('gdelt_parquet_db/gdelt_2015-02.parquet')
LIMIT 5;
"""
con.execute(query_setup)

# 2. Matching en incluant EnhancedThemes dans les colonnes transportées
sector_themes = pd.DataFrame({
    'cat_key': ['GENERAL_GOVERNMENT', 'TAX_WORLDLANGUAGES', 'CHECKPOINT'],
    'theme': ['GENERAL_GOVERNMENT', 'TAX_WORLDLANGUAGES', 'CHECKPOINT'] # Remplace par tes thèmes réels
})
con.register("sector_themes_tbl", sector_themes)

query_matching = """
WITH 
unnested AS (
    -- On ajoute EnhancedThemes ici pour le garder dans le résultat final
    SELECT GKGRECORDID, EnhancedThemes, period, tone, tone_bin, total_themes_count, unnest(themes_list) as theme
    FROM gkg_clean
),

matched AS (
    SELECT 
        u.GKGRECORDID, u.EnhancedThemes, u.period, u.tone, u.tone_bin, u.total_themes_count,
        st.cat_key,
        COUNT(*) AS theme_hits
    FROM unnested u
    INNER JOIN sector_themes_tbl st ON u.theme = st.theme
    GROUP BY 1, 2, 3, 4, 5, 6, 7
)

SELECT * FROM matched
"""

resultat = con.execute(query_matching).df()
display(resultat)

,GKGRECORDID,EnhancedThemes,period,tone,tone_bin,total_themes_count,cat_key,theme_hits
0,20150219071500-0,"KILL,464;SEIGE,3001;CHECKPOINT,3001;UNREST_CHECKPOINT,3001;WOUND,511;MILITARY,1502;TAX_MILITARY_TITLE,1502;TAX_FNCACT,1502;TAX_FNCACT,1805;TAX_WORLDLANGUAGES,841;TAX_WORLDLANGUAGES,866;SOC_SUICIDE,229;SOC_SUICIDE,397;SOC_SUICIDE,739;SOC_SUICIDE,1586;SOC_SUICIDE,1900;SOC_SUICIDE,2328;SOC_SUICIDE,2664;TAX_FNCACT,2099;TAX_FNCACT,188;TAX_FNCACT,168;ARMEDCONFLICT,574;TAX_FNCACT,1246;SOC_POINTSOFINTEREST,45;SOC_POINTSOFINTEREST,141;SOC_POINTSOFINTEREST,270;SOC_POINTSOFINTEREST,342;SOC_POINTSOFINTEREST,373;SOC_POINTSOFINTEREST,454;SOC_POINTSOFINTEREST,659;SOC_POINTSOFINTEREST,787;SOC_POINTSOFINTEREST,1066;SOC_POINTSOFINTEREST,1233;SOC_POINTSOFINTEREST,1761;SOC_POINTSOFINTEREST,2140;SOC_POINTSOFINTEREST,2262;SOC_POINTSOFINTEREST,2410;TAX_WEAPONS,2334;TAX_WEAPONS,1119;PROTEST,761;TAX_WEAPONS,1593;TAX_WEAPONS,2671;SECURITY_SERVICES,32;SECURITY_SERVICES,159;SECURITY_SERVICES,257;SECURITY_SERVICES,360;SECURITY_SERVICES,415;SECURITY_SERVICES,646;SECURITY_SERVICES,774;SECURITY_SERVICES,857;SECURITY_SERVICES,879;SECURITY_SERVICES,1053;SECURITY_SERVICES,1220;SECURITY_SERVICES,2295;SECURITY_SERVICES,2397;SECURITY_SERVICES,2799;SECURITY_SERVICES,2851;SECURITY_SERVICES,2913;TAX_FNCACT,32;TAX_FNCACT,159;TAX_FNCACT,257;TAX_FNCACT,360;TAX_FNCACT,415;TAX_FNCACT,646;TAX_FNCACT,774;TAX_FNCACT,857;TAX_FNCACT,879;TAX_FNCACT,1053;TAX_FNCACT,1220;TAX_FNCACT,2295;TAX_FNCACT,2397;TAX_FNCACT,2799;TAX_FNCACT,2851;TAX_FNCACT,2913;TAX_FNCACT,2420;TERROR,237;TERROR,405;TERROR,1908;SUICIDE_ATTACK,237;SUICIDE_ATTACK,405;SUICIDE_ATTACK,1908;TAX_WEAPONS,237;TAX_WEAPONS,405;TAX_WEAPONS,1908;TAX_FNCACT,715;",2015-02-19,-4.644531,-1,86,CHECKPOINT,1
1,20150219020000-1,"TRAFFIC,986;DISCRIMINATION,569;ARREST,1012;TRIAL,9;TAX_FNCACT,9;TAX_MILITARY_TITLE,917;TAX_FNCACT,917;SECURITY_SERVICES,191;SECURITY_SERVICES,376;SECURITY_SERVICES,605;SECURITY_SERVICES,1144;SECURITY_SERVICES,1177;TAX_FNCACT,191;TAX_FNCACT,376;TAX_FNCACT,605;TAX_FNCACT,1144;TAX_FNCACT,1177;TAX_MILITARY_TITLE,294;TAX_FNCACT,294;TAX_WORLDLANGUAGES,753;",2015-02-19,-2.068359,-1,21,TAX_WORLDLANGUAGES,1
2,20150219020000-3,"TAX_WORLDLANGUAGES,2843;TAX_FNCACT,3153;TAX_FNCACT,3408;TAX_FNCACT,3436;TAX_FNCACT,3096;TAX_FNCACT,3336;EDUCATION,1018;EDUCATION,1126;EDUCATION,2646;SOC_POINTSOFINTEREST,1018;SOC_POINTSOFINTEREST,1126;SOC_POINTSOFINTEREST,2646;TAX_WORLDMAMMALS,2086;ENV_OIL,2975;LEADER,1057;LEADER,2587;TAX_FNCACT,1057;TAX_FNCACT,2587;TAX_FNCACT,2891;MEDIA_SOCIAL,2516;TAX_FNCACT,3618;TAX_FNCACT,3048;TAX_WORLDFISH,2202;TAX_POLITICAL_PARTY,354;SOC_POINTSOFINTEREST,1888;SOC_POINTSOFINTEREST,3781;TAX_FNCACT,1286;TAX_FNCACT,1346;TAX_FNCACT,48;TAX_FNCACT,132;TAX_FNCACT,570;TAX_FNCACT,623;TAX_FNCACT,988;TAX_FNCACT,2463;TAX_FNCACT,2600;SECURITY_SERVICES,1323;SECURITY_SERVICES,1776;TAX_FNCACT,1323;TAX_FNCACT,1776;EXTREMISM,2539;TAX_MILITARY_TITLE,3637;TAX_FNCACT,3637;TAX_FNCACT,1683;",2015-02-19,-1.104492,-1,44,TAX_WORLDLANGUAGES,1
3,20150219020000-2,"GENERAL_GOVERNMENT,2276;ECON_INTEREST_RATES,2246;ECON_STOCKMARKET,1857;TAX_WORLDMAMMALS,1601;TAX_WORLDMAMMALS,1700;TAX_WORLDMAMMALS,2121;KILL,39;KILL,1297;TAX_FNCACT,95;LEADER,107;TAX_FNCACT,107;MEDIA_MSM,832;ECON_DEBT,1948;",2015-02-19,-2.250000,-1,14,GENERAL_GOVERNMENT,1
4,20150219071500-0,"KILL,464;SEIGE,3001;CHECKPOINT,3001;UNREST_CHECKPOINT,3001;WOUND,511;MILITARY,1502;TAX_MILITARY_TITLE,1502;TAX_FNCACT,1502;TAX_FNCACT,1805;TAX_WORLDLANGUAGES,841;TAX_WORLDLANGUAGES,866;SOC_SUICIDE,229;SOC_SUICIDE,397;SOC_SUICIDE,739;SOC_SUICIDE,1586;SOC_SUICIDE,1900;SOC_SUICIDE,2328;SOC_SUICIDE,2664;TAX_FNCACT,2099;TAX_FNCACT,188;TAX_FNCACT,168;ARMEDCONFLICT,574;TAX_FNCACT,1246;SOC_POINTSOFINTEREST,45;SOC_POINTSOFINTEREST,141;SOC_POINTSOFINTEREST,270;SOC_POINTSOFINTEREST,342;SOC_POINTSOFINTEREST,373;SOC_POINTSOFINTEREST,454;SOC_POINTSOFINTEREST,659;SOC_POINTSOFINTEREST,787;SOC_POINTSOFINTEREST,1066;SOC_POINTSOFINTEREST,1233;SOC_POINTSOFINTEREST,1761;SOC_POINTSOFINTEREST,2140;SOC_POINTSOFINTEREST,2262;SOC_POINTSOFINTEREST,2410;TAX_WEAPONS,2334;TAX_WEAPONS,1119;PROTEST,761;TAX_WEAPONS,1593;TAX_WEAPONS,2671;SECURITY_SERVICES,32;SECURITY_SERVICES,159;SECURITY_SERVICES,257;SECURITY_SERVICES,360;SECURITY_SERVICES,415;SECURITY_SERVICES,646;SECURITY_SERVICES,774;SECURITY_SERVICES,857;SECURITY_SERVICES,879;SECURITY_SERVICES,1053;SECURITY_SERVICES,1220;SECURITY_SERVICES,2295;SECURITY_SERVICES,2397;SECURITY_SERVICES,2799;SECURITY_SERVICES,2851;SECURITY_SERVICES,2913;TAX_FNCACT,32;TAX_FNCACT,159;TAX_FNCACT,257;TAX_FNCACT,360;TAX_FNCACT,415;TAX_FNCACT,646;TAX_FNCACT,774;TAX_FNCACT,857;TAX_FNCACT,879;TAX_FNCACT,1053;TAX_FNCACT,1220;TAX_FNCACT,2295;TAX_FNCACT,2397;TAX_FNCACT,2799;TAX_FNCACT,2851;TAX_FNCACT,2913;TAX_FNCACT,2420;TERROR,237;TERROR,405;TERROR,1908;SUICIDE_ATTACK,237;SUICIDE_ATTACK,405;SUICIDE_ATTACK,1908;TAX_WEAPONS,237;TAX_WEAPONS,405;TAX_WEAPONS,1908;TAX_FNCACT,715;",2015-02-19,-4.644531,-1,86,TAX_WORLDLANGUAGES,2

In [34]:
import duckdb
import pandas as pd
from pathlib import Path

def explore_gdelt_locations(parquet_file_path: str, limit: int = 20):
    """
    Explore et compte les localisations (Pays et Villes) contenues dans un fichier GDELT brut.
    
    Paramètres:
    - parquet_file_path: Chemin vers un fichier parquet brut (ex: './gdelt_parquet_db_test/gdelt_202001.parquet')
    - limit: Nombre de résultats à afficher
    """
    
    # On se connecte en mémoire vive pour cette petite exploration
    con = duckdb.connect(database=':memory:')
    
    # La requête magique qui déplie et parse la chaîne complexe de GDELT
    query = f"""
    WITH unnested_locs AS (
        -- 1. On sépare chaque bloc de localisation (découpé par ;)
        SELECT unnest(string_split(EnhancedLocations, ';')) AS loc_str
        FROM read_parquet('{parquet_file_path}')
        WHERE EnhancedLocations IS NOT NULL AND EnhancedLocations != ''
    ),
    parsed_locs AS (
        -- 2. On découpe l'intérieur du bloc (découpé par #)
        SELECT 
            split_part(loc_str, '#', 1) AS LocType,
            split_part(loc_str, '#', 2) AS LocName,
            split_part(loc_str, '#', 3) AS CountryCode
        FROM unnested_locs
        WHERE loc_str != ''
    )
    -- 3. On compte et on trie
    SELECT 
        LocType,
        CountryCode,
        LocName,
        COUNT(*) AS mentions
    FROM parsed_locs
    WHERE CountryCode != ''
    GROUP BY LocType, CountryCode, LocName
    ORDER BY mentions DESC
    LIMIT {limit};
    """
    
    print(f"Analyse des localisations en cours sur {parquet_file_path} ...")
    df_locs = con.execute(query).df()
    
    # Petit dictionnaire pour rendre le LocType lisible
    type_map = {
        '1': 'Pays', 
        '2': 'État US', 
        '3': 'Ville US', 
        '4': 'Ville Monde', 
        '5': 'Région Monde'
    }
    df_locs['Type_Clair'] = df_locs['LocType'].map(type_map).fillna('Inconnu')
    
    # Réorganisation des colonnes pour un affichage propre
    df_locs = df_locs[['Type_Clair', 'CountryCode', 'LocName', 'mentions']]
    
    con.close()
    return df_locs

# ── EXEMPLE D'UTILISATION ──
# Pointez vers UN SEUL fichier de votre base de données brute (pas les indicateurs générés)
fichier_test = "./gdelt_parquet_db/gdelt_2026-05.parquet" # <- À modifier avec votre vrai chemin

if Path(fichier_test).exists():
    df_top_locations = explore_gdelt_locations(fichier_test, limit=60)
    display(df_top_locations)
else:
    print(f"Fichier introuvable : {fichier_test}. Modifiez le chemin.")

Analyse des localisations en cours sur ./gdelt_parquet_db/gdelt_2026-05.parquet ...

,Type_Clair,CountryCode,LocName,mentions
0,Pays,CH,China,3445961
1,Pays,IR,Iran,2743911
2,Pays,US,United States,2112431
3,Pays,RS,Russia,1583906
4,Pays,UP,Ukraine,1443390
5,Pays,IN,India,1354276
6,Pays,UK,United Kingdom,1255006
7,Pays,IS,Israel,1098005
8,Pays,RS,Russian,942217
9,Pays,GM,Germany,871467
10,Pays,IT,Italy,801703
11,Pays,TW,Taiwan,794839
12,Pays,MX,Mexico,784071
13,Pays,US,American,763118
14,Pays,SP,Spain,749449
15,Pays,CA,Canada,743186
16,Pays,TU,Turkey,704811
17,Pays,CH,Chinese,699564
18,Pays,AS,Australia,658037
19,Ville US,US,"Washington, Washington, United States",629053
20,Pays,FR,France,628334
21,Pays,JA,Japan,573456
22,Pays,VM,Vietnam,556175
23,Pays,UP,Ukrainian,514547
24,Ville Monde,CH,"Beijing, Beijing, China",496320
25,Pays,GM,German,495473
26,Pays,US,America,487205
27,Pays,IT,Italian,473832
28,Pays,BR,Brazil,464201
29,État US,US,"New York, United States",456620
30,Pays,ID,Indonesia,440328
31,Pays,IR,Iranian,420335
32,Ville Monde,RS,"Moscow, Moskva, Russia",417141
33,Pays,FR,French,414575
34,Pays,IS,Israeli,400832
35,Ville Monde,UK,"London, London, City Of, United Kingdom",394226
36,Pays,GR,Greece,377530
37,Pays,AR,Argentina,365310
38,Ville Monde,IR,"Tehran, Tehran, Iran",358321
39,Pays,SP,Spanish,353881
40,Pays,PK,Pakistan,352364
41,État US,US,"California, United States",347691
42,Pays,RO,Romania,341943
43,Pays,LE,Lebanon,334064
44,Pays,CO,Colombia,297984
45,État US,US,"Texas, United States",280075
46,Ville US,US,"White House, District Of Columbia, United States",270618
47,Pays,SW,Suede,265653
48,Pays,PL,Poland,260554
49,Pays,CU,Cuba,247363
50,Pays,UK,British,235256
51,Pays,VE,Venezuela,233878
52,Pays,EG,Egypt,232363
53,Pays,GR,Greek,227915
54,Pays,NI,Nigeria,223242
55,Ville Monde,IT,"Rome, Lazio, Italy",220571
56,Pays,HK,Hong Kong,217631
57,Pays,AS,Australian,216039
58,Pays,CA,Canadian,210048
59,Pays,TH,Thailand,203948